#!/usr/bin/env bash 

cd .. 

echo "Running sim_scripts/pn-lc-mi-sim_setting-1.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-1.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-2.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-2.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-3.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-3.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-4.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-4.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-5.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-5.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-6.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-6.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-7.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-7.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-8.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-8.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-9.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-9.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-10.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-10.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-11.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-11.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-12.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-12.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-13.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-13.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-14.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-14.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-15.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-15.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-16.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-16.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-17.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-17.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-18.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-18.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-19.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-19.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-20.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-20.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-21.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-21.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-22.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-22.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-23.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-23.R"
echo "Running sim_scripts/pn-lc-mi-sim_setting-24.R" 
time Rscript "sim_scripts/pn-lc-mi-sim_setting-24.R"

echo "Done!"
